#
# Copyright (c) Dell Inc., or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#

{{- if $.Values.enabled }}
{{- range $s := until (int $.Values.global.pravega.numStreams) }}
{{- range $r := until (int $.Values.numReadersPerStream) }}

{{- $alias := "" }}
{{- if $.Values.alias }}
  {{- $alias = print "-" $.Values.alias }}
{{- end }}

{{- $streamSuffix := "" }}
{{- if (gt (int $.Values.global.pravega.numStreams) 1) }}
  {{- $streamSuffix = print "-" $s }}
{{- end }}
{{- $suffix := print $streamSuffix "-" $r }}

{{- $name := print $.Release.Name $alias $suffix }}

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $name }}
  labels: 
    release: {{ $name }}
spec:
  serviceName: {{ $name }}
  selector:
    matchLabels:
      release: {{ $name }}
  template:
    metadata:
      labels:
        release: {{ $name }}
    spec:
      serviceAccount: {{ $.Release.Namespace }}-pravega
      containers:
      - name: gstreamer
        image: {{ $.Values.image.repository | quote }}
        imagePullPolicy: {{ $.Values.image.pullPolicy | quote }}
        resources:
{{ toYaml $.Values.resources | indent 10 }}  
        workingDir: /usr/src/gstreamer-pravega
        command: ["bash", "-c", "--"]
        args:
          - mkdir -p ${LOG_DIR} &&
            longevity-test |& tee ${LOG_DIR}/${PRAVEGA_STREAM}_${HOSTNAME}.log
        env:
        - name: LOG_DIR
          value: "/mnt/logs/test-logs"
        - name: PRAVEGA_STREAM
          value: "{{ $.Values.global.pravega.stream }}{{ $streamSuffix }}"
        {{- range $key, $value := $.Values.appParameters }}
        - name: {{ $key | quote }}
          value: {{ $value | quote }}
        {{- end }}
        volumeMounts:
        - mountPath: /mnt/logs/
          name: logs
      volumes:
      - name: logs
        persistentVolumeClaim:
          claimName: {{ $.Values.logPersistentVolumeClaimName }}
---

{{- end }}
{{- end }}
{{- end }}
