#
# Copyright (c) Dell Inc., or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rtsp-camera-simulator
  labels: 
    release: rtsp-camera-simulator
spec:
  selector:
    matchLabels:
      release: rtsp-camera-simulator
  template:
    metadata:
      labels:
        release: rtsp-camera-simulator
    spec:
      containers:
      - name: rtsp-camera-simulator
        image: {{ .Values.image.repository | quote }}
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        command: ["rtsp-camera-simulator"]
        ports:
        - name: rtsp
          containerPort: 8554
          protocol: TCP
        env:
        - name: CAMERA_PASSWORD
          value: {{ .Values.camera.password | quote }}
        - name: CAMERA_PORT
          value: "8554"
        - name: CAMERA_USER
          value: {{ .Values.camera.user | quote }}
