apiVersion: v1
kind: Service
metadata:
  name: rtsp-camera-simulator
spec:
  ports:
  - name: rtsp
    port: 8554
    targetPort: 8554
    protocol: TCP
  selector:
    release: rtsp-camera-simulator
  type: LoadBalancer
