#
# Copyright (c) Dell Inc., or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#

{{- range $i := until (int $.Values.numStreams) }}

{{- $suffix := "" }}
{{- if (gt (int $.Values.numStreams) 1) }}
  {{- $suffix = print "-" $i }}
{{- end }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}{{ $suffix }}
  labels: 
    release: {{ $.Release.Name }}{{ $suffix }}
spec:
  selector:
    matchLabels:
      release: {{ $.Release.Name }}{{ $suffix }}
  template:
    metadata:
      labels:
        release: {{ $.Release.Name }}{{ $suffix }}
    spec:
      serviceAccount: {{ $.Release.Namespace }}-pravega
      containers:
      - name: gstreamer
        image: {{ $.Values.image.repository | quote }}
        imagePullPolicy: {{ $.Values.image.pullPolicy | quote }}
        command: ["rtsp-camera-to-pravega.py"]
        env:
        - name: PRAVEGA_STREAM
          value: "{{ $.Values.pravegaStream }}{{ $suffix }}"
        {{- if .Values.healthCheck.enabled }}
        - name: HEALTH_CHECK_ENABLED
          value: "true"
        - name: HEALTH_CHECK_IDLE_SECONDS
          value: {{ .Values.healthCheck.idleSeconds | quote }}
        {{- end }}
        {{- range $key, $value := $.Values.appParameters }}
        - name: {{ $key | quote }}
          value: {{ $value | quote }}
        {{- end }}
        {{- if $.Values.healthCheck.enabled }}
        livenessProbe:
          httpGet:
            path: /ishealthy
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 3
        {{- end }}
---

{{- end }}
