#
# Copyright (c) Dell Inc., or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#

{{- if $.Values.enabled }}
{{- range $i := until (int $.Values.global.pravega.numStreams) }}

{{- $alias := "" }}
{{- if $.Values.alias }}
  {{- $alias = print "-" $.Values.alias }}
{{- end }}

{{- $suffix := "" }}
{{- if (gt (int $.Values.global.pravega.numStreams) 1) }}
  {{- $suffix = print "-" $i }}
{{- end }}

{{- $name := print $.Release.Name $alias $suffix }}

{{- $cameraAddress := "" }}
{{- if $.Values.global.camera.address }}
  {{- $cameraAddress =  $.Values.global.camera.address }}
{{- else }}
  {{- $cameraAddress = print $.Release.Name "-simulator" }}
{{- end }}

{{- if not $.Values.useGStreamerOperator }}

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $name }}
  labels: 
    release: {{ $name }}
spec:
  serviceName: {{ $name }}
  selector:
    matchLabels:
      release: {{ $name }}
  template:
    metadata:
      labels:
        release: {{ $name }}
    spec:
      serviceAccount: {{ $.Release.Namespace }}-pravega
      containers:
      - name: gstreamer
        image: {{ $.Values.image.repository | quote }}
        imagePullPolicy: {{ $.Values.image.pullPolicy | quote }}
        command: ["bash", "-c", "--"]
        args:
          - mkdir -p ${LOG_DIR} &&
            rtsp-camera-to-pravega.py |& tee ${LOG_DIR}/${PRAVEGA_STREAM}_${HOSTNAME}.log
        env:
        - name: CAMERA_ADDRESS
          value: {{ $cameraAddress | quote }}
        - name: CAMERA_USER
          valueFrom:
            secretKeyRef:
              key: "username"
              name: {{ $.Release.Name | quote }}
        - name: CAMERA_PASSWORD
          valueFrom:
            secretKeyRef:
              key: "password"
              name: {{ $.Release.Name | quote }}
        - name: CAMERA_PATH
          value: {{ $.Values.global.camera.path | quote }}
        - name: CAMERA_PORT
          value: {{ $.Values.global.camera.rtspPort | quote }}
        - name: PRAVEGA_STREAM
          value: "{{ $.Values.global.pravega.stream }}{{ $suffix }}"
        - name: LOG_DIR
          value: "/mnt/logs/test-logs"
        {{- if $.Values.healthCheck.enabled }}
        - name: HEALTH_CHECK_ENABLED
          value: "true"
        - name: HEALTH_CHECK_IDLE_SECONDS
          value: {{ $.Values.healthCheck.idleSeconds | quote }}
        {{- end }}
        {{- range $key, $value := $.Values.appParametersStatefulSet }}
        - name: {{ $key | quote }}
          value: {{ $value | quote }}
        {{- end }}
        {{- range $key, $value := $.Values.appParameters }}
        - name: {{ $key | quote }}
          value: {{ $value | quote }}
        {{- end }}
        {{- if $.Values.healthCheck.enabled }}
        startupProbe:
          httpGet:
            path: /ishealthy
            port: 8080
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /ishealthy
            port: 8080
          periodSeconds: 3
        livenessProbe:
          httpGet:
            path: /ishealthy
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 3
        {{- end }}
        volumeMounts:
        - mountPath: /mnt/logs/
          name: logs
      volumes:
      - name: logs
        persistentVolumeClaim:
          claimName: {{ $.Values.logPersistentVolumeClaimName }}
---

{{- else }}

apiVersion: gstreamer.dellemc.com/v1alpha1
kind: CameraRecorderPipeline
metadata:
  name: {{ $name }}
spec:
  image: {{ $.Values.image.repository | quote }}
  pullPolicy: {{ $.Values.image.pullPolicy | quote }}
  camera:
    address: {{ $cameraAddress | quote }}
    path: {{ $.Values.global.camera.path | quote }}
    port: {{ $.Values.global.camera.rtspPort | quote }}
    secret: {{ $.Release.Name | quote }}
  pravega:
    retentionPolicy:
{{ toYaml $.Values.pravega.retentionPolicy | indent 6 }}  
    stream: "{{ $.Values.global.pravega.stream }}{{ $suffix }}"
  env:
  {{- if $.Values.healthCheck.enabled }}
  - name: HEALTH_CHECK_IDLE_SECONDS
    value: {{ $.Values.healthCheck.idleSeconds | quote }}
  {{- end }}
  {{- range $key, $value := $.Values.appParameters }}
  - name: {{ $key | quote }}
    value: {{ $value | quote }}
  {{- end }}
  resources:
{{ toYaml $.Values.resources | indent 4 }}  
  state: Running
---

{{- end }}
{{- end }}
{{- end }}
