#!/bin/bash

#
# Copyright (c) Dell Inc., or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#

set -ex

for repo in gstreamer libnice gst-plugins-base gst-plugins-bad gst-plugins-good gst-plugins-ugly gst-libav gst-rtsp-server; do
  pushd $repo

  opts="-D prefix=/usr"

  if [[ $repo == "libnice" ]]; then
    # TODO: Hack: `-D gupnp=disabled` is for libnice, because libgupnp-igd causes memory leaks
    opts="$opts -D gupnp=disabled"
  elif [[ $repo == "gst-plugins-base" ]]; then
    opts="$opts -D gl=disabled"
  elif [[ $repo == "gst-plugins-bad" ]]; then
    opts="$opts -D gl=disabled -D msdk=enabled"
  fi

  if [[ $DEBUG == 'true' ]]; then
    if [[ $OPTIMIZATIONS == 'true' ]]; then
      opts="$opts -D debug=true -D optimization=2"
    else
      opts="$opts -D debug=true"
    fi
  else
    opts="$opts -D debug=false -D optimization=3 -D b_lto=true -D buildtype=release"
  fi

  meson build $opts

  # This is needed for other plugins to be built properly
  ninja -C build install
  # This is where we'll grab build artifacts from
  DESTDIR=/compiled-binaries ninja -C build install
  popd
done

gst-inspect-1.0
