#!/bin/bash

#
# Copyright (c) Dell Inc., or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#

set -ex

checkoutInRepo() {
    pushd $1
    git checkout $2
    popd
}

git clone --no-checkout "$GSTREAMER_REPOSITORY" &
git clone --no-checkout "$LIBNICE_REPOSITORY" &

wait

checkoutInRepo gstreamer "$GSTREAMER_CHECKOUT"
checkoutInRepo libnice "$LIBNICE_CHECKOUT"
