#!/bin/bash

#
# Copyright (c) Dell Inc., or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#

set -ex

export DEBIAN_FRONTEND=noninteractive

sed -i 's/# deb-src/deb-src/g' /etc/apt/sources.list
apt-get update
apt-get dist-upgrade -y

apt-get install -y --no-install-recommends \
  bison \
  bubblewrap \
  ca-certificates \
  cmake \
  flex \
  flite1-dev \
  gcc \
  gettext \
  git \
  gperf \
  intel-media-va-driver-non-free \
  iso-codes \
  less \
  liba52-0.7.4-dev \
  libaa1-dev \
  libaom-dev \
  libatk1.0-dev \
  libass-dev \
  libavcodec-dev \
  libavfilter-dev \
  libavformat-dev \
  libavutil-dev \
  libbs2b-dev \
  libbz2-dev \
  libcaca-dev \
  libcap-dev \
  libchromaprint-dev \
  libcurl4-gnutls-dev \
  libdca-dev \
  libde265-dev \
  libdrm-dev \
  libdv4-dev \
  libdvdnav-dev \
  libdvdread-dev \
  libdw-dev \
  libepoxy-dev \
  libfaac-dev \
  libfaad-dev \
  libfdk-aac-dev \
  libfluidsynth-dev \
  libgbm-dev \
  libgcrypt20-dev \
  libgirepository1.0-dev \
  libgl-dev \
  libgles-dev \
  libglib2.0-dev \
  libgme-dev \
  libgmp-dev \
  libgsl-dev \
  libgsm1-dev \
  libgtk-3-dev \
  libgudev-1.0-dev \
  libjpeg-dev \
  libkate-dev \
  liblcms2-dev \
  liblilv-dev \
  libmfx-dev \
  libmjpegtools-dev \
  libmodplug-dev \
  libmp3lame-dev \
  libmpcdec-dev \
  libmpeg2-4-dev \
  libmpg123-dev \
  libofa0-dev \
  libogg-dev \
  libopencore-amrnb-dev \
  libopencore-amrwb-dev \
  libopenexr-dev \
  libopenjp2-7-dev \
  libopus-dev \
  liborc-0.4-dev \
  libpango1.0-dev \
  libpng-dev \
  librsvg2-dev \
  librtmp-dev \
  libsbc-dev \
  libseccomp-dev \
  libshout3-dev \
  libsndfile1-dev \
  libsoundtouch-dev \
  libsoup2.4-dev \
  libspandsp-dev \
  libspeex-dev \
  libsrt-gnutls-dev \
  libsrtp2-dev \
  libssl-dev \
  libtag1-dev \
  libtheora-dev \
  libtwolame-dev \
  libudev-dev \
  libunwind-dev \
  libva-dev \
  libvisual-0.4-dev \
  libvo-aacenc-dev \
  libvo-amrwbenc-dev \
  libvorbis-dev \
  libvpx-dev \
  libvulkan-dev \
  libwavpack-dev \
  libwayland-dev \
  libwebp-dev \
  libwebrtc-audio-processing-dev \
  libwildmidi-dev \
  libwoff-dev \
  libx264-dev \
  libx265-dev \
  libxkbcommon-dev \
  libxslt1-dev \
  libzbar-dev \
  libzvbi-dev \
  netcat-openbsd \
  python-gi-dev \
  python3 \
  python3-gi \
  python3-gi-cairo \
  python3-pip \
  ruby \
  wayland-protocols \
  wget \
  xdg-dbus-proxy

pip3 install \
  configargparse \
  meson \
  ninja

apt-get clean
rm -rf /var/lib/apt/lists/*
