#
# Copyright (c) Dell Inc., or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#

enabled: true
image:
  # Please change the value accordingly before deployment
  repository: "gstreamer:pravega-dev"
  pullPolicy: "Always"
appParameters:
  # See available application parameters in https://github.com/pravega/gstreamer-pravega/blob/master/integration-test/src/bin/longevity-test.rs
  ALLOW_CREATE_SCOPE: "false"
  CONTAINER_FORMAT: "mp4"
  pravega_client_tls_cert_path: "/etc/ssl/certs/ca-certificates.crt"
numReadersPerStream: 1
logPersistentVolumeClaimName: data-project
global:
  pravega:
    stream: "camera1"
    numStreams: 1
