# Kubernetes deployment for rtsp-camera-to-pravega.py.
#
# Install with:
#   kubectl -n examples create secret generic camera-group-1 --type=kubernetes.io/basic-auth --from-literal=username=yourname --from-literal=password=yourpassword
#   kubectl -n examples apply -f rtsp-camera-to-pravega-sample.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rtsp-camera-to-pravega-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rtsp-camera-to-pravega-1
  template:
    metadata:
      labels:
        app: rtsp-camera-to-pravega-1
    spec:
      serviceAccount: examples-pravega
      containers:
      - name: gstreamer
        image: devops-repo.isus.emc.com:8116/nautilus/gstreamer:pravega-dev
        imagePullPolicy: Always
        command: ["rtsp-camera-to-pravega.py"]
        env:
        - name: ALLOW_CREATE_SCOPE
          value: "false"
        - name: CAMERA_ADDRESS
          value: "10.246.27.131"
        - name: CAMERA_PATH
          value: "/cam/realmonitor?target_rate_KB_per_sec=10"
        - name: CAMERA_PORT
          value: "8554"
        - name: CAMERA_PROTOCOLS
          value: "tcp"
        - name: CAMERA_USER
          valueFrom:
            secretKeyRef:
              name: camera-group-1
              key: username
        - name: CAMERA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: camera-group-1
              key: password
        - name: FAKESINK
          value: "false"
        - name: GST_DEBUG
          value: "WARNING,rtspsrc:INFO,rtpbin:INFO,rtpsession:INFO,rtpjitterbuffer:INFO,h264parse:WARN,pravegasink:LOG"
        - name: pravega_client_tls_cert_path
          value: "/etc/ssl/certs/DST_Root_CA_X3.pem"
        - name: PRAVEGA_STREAM
          value: "video18"
