# Kubernetes deployment for rtsp-camera-to-pravega.py.
#
# Install with:
#   kubectl -n examples create secret generic camera-group-1 --type=kubernetes.io/basic-auth --from-literal=username=yourname --from-literal=password=yourpassword
#   kubectl -n examples apply -f deployment1.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rtsp-camera-to-pravega-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rtsp-camera-to-pravega-1
  template:
    metadata:
      labels:
        app: rtsp-camera-to-pravega-1
    spec:
      containers:
      - name: gstreamer
        image: devops-repo.isus.emc.com:8116/nautilus/gstreamer:pravega-dev
        imagePullPolicy: Always
        command: ["rtsp-camera-to-pravega.py"]
        env:
        - name: ALLOW_CREATE_SCOPE
          value: "false"
        - name: CAMERA_ADDRESS
          value: "10.246.27.131"
        - name: CAMERA_PATH
          value: "/cam/realmonitor?target_rate_KB_per_sec=5"
        - name: CAMERA_PORT
          value: "8554"
        - name: CAMERA_USER
          valueFrom:
            secretKeyRef:
              name: camera-group-1
              key: username
        - name: CAMERA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: camera-group-1
              key: password
        - name: pravega_client_auth_keycloak
          value: /var/run/secrets/nautilus.dellemc.com/serviceaccount/keycloak.json
        - name: pravega_client_auth_method
          value: "Bearer"
        - name: pravega_client_tls_cert_path
          value: "/etc/ssl/certs/DST_Root_CA_X3.pem"
        - name: PRAVEGA_CONTROLLER_URI
          value: "tls://pravega-controller.kubespray.nautilus-platform-dev.com:443"
        - name: PRAVEGA_SCOPE
          value: examples
        - name: PRAVEGA_STREAM
          value: "video13"
        volumeMounts:
        - mountPath: /var/run/secrets/nautilus.dellemc.com/serviceaccount
          name: keycloak
          readOnly: true
      volumes:
      - name: keycloak
        secret:
          defaultMode: 420
          secretName: examples-pravega
