#
# Copyright (c) Dell Inc., or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#

FROM ubuntu:20.10

COPY docker/build-gstreamer/install-dependencies /

RUN ["/install-dependencies"]

COPY ca-certificates /usr/local/share/ca-certificates/
RUN update-ca-certificates
