#
# Copyright (c) Dell Inc., or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#

FROM pravega/gstreamer:latest-dev-with-source

# Only development dependencies
FROM pravega/gstreamer:dev-dependencies

# And binaries built with debug symbols
COPY --from=0 /compiled-binaries /
