#
# Copyright (c) Dell Inc., or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#

{{- range $s := until (int $.Values.numStreams) }}
{{- range $r := until (int $.Values.numReadersPerStream) }}

{{- $streamSuffix := "" }}
{{- if (gt (int $.Values.numStreams) 1) }}
  {{- $streamSuffix = print "-" $s }}
{{- end }}
{{- $suffix := print $streamSuffix "-" $r }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}{{ $suffix }}
  labels: 
    release: {{ $.Release.Name }}{{ $suffix }}
spec:
  selector:
    matchLabels:
      release: {{ $.Release.Name }}{{ $suffix }}
  template:
    metadata:
      labels:
        release: {{ $.Release.Name }}{{ $suffix }}
    spec:
      serviceAccount: {{ $.Release.Namespace }}-pravega
      containers:
      - name: gstreamer
        image: {{ $.Values.image.repository | quote }}
        imagePullPolicy: {{ $.Values.image.pullPolicy | quote }}
        resources:
          limits:
            cpu: "4"
            memory: "1Gi"
          requests:
            cpu: "4"
            memory: "1Gi"
        workingDir: /usr/src/gstreamer-pravega
        command: ["bash", "-c", "--"]
        args:
          - mkdir -p ${LOG_DIR} &&
            longevity-test |& tee ${LOG_DIR}/${LOG_FILE}
        env:
        - name: LOG_DIR
          value: "/mnt/logs/test-logs"
        - name: LOG_FILE
          value: "{{ $.Release.Name }}{{ $suffix }}.log"
        - name: PRAVEGA_STREAM
          value: "{{ $.Values.pravegaStream }}{{ $streamSuffix }}"
        {{- range $key, $value := $.Values.appParameters }}
        - name: {{ $key | quote }}
          value: {{ $value | quote }}
        {{- end }}
        volumeMounts:
        - mountPath: /mnt/logs/
          name: logs
      volumes:
      - name: logs
        persistentVolumeClaim:
          claimName: {{ $.Values.logPersistentVolumeClaimName }}
---

{{- end }}
{{- end }}
