#
# Copyright (c) Dell Inc., or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#

enabled: true
image:
  # Please change the value accordingly before deployment
  repository: "gstreamer:pravega-dev"
  pullPolicy: "Always"
appParameters:
  # See available application parameters in https://github.com/pravega/gstreamer-pravega/blob/master/apps/src/bin/rtsp-camera-simulator.rs
  CAMERA_HEIGHT: "640"
  CAMERA_WIDTH: "480"
  CAMERA_FPS: "30"
  CAMERA_KEY_FRAME_INTERVAL_MAX: "30"
  CAMERA_SHOW_CLOCK: "1"
  CAMERA_TARGET_RATE_KILOBYTES_PER_SEC: "250.0"
replicas: 1
global:
  camera:
    rtspPort: 8554
    tlsEnabled: false
