#!/bin/bash

#
# Copyright (c) Dell Inc., or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#

set -ex

for repo in gstreamer libnice gst-plugins-base gst-plugins-bad gst-plugins-good gst-plugins-ugly gst-libav gst-rtsp-server; do
  pushd $repo
  # TODO: Hack: `-D gupnp=disabled` is for libnice, because libgupnp-igd causes memory leaks
  if [[ $DEBUG == 'true' ]]; then
    if [[ $OPTIMIZATIONS == 'true' ]]; then
      meson build -D prefix=/usr -D gupnp=disabled -D msdk=enabled -D debug=true -D optimization=2
    else
      meson build -D prefix=/usr -D gupnp=disabled -D msdk=enabled -D debug=true
    fi
  else
    meson build -D prefix=/usr -D gupnp=disabled -D msdk=enabled -D debug=false -D optimization=3 -D b_lto=true -D buildtype=release
  fi
  # This is needed for other plugins to be built properly
  ninja -C build install
  # This is where we'll grab build artifacts from
  DESTDIR=/compiled-binaries ninja -C build install
  popd
done

gst-inspect-1.0
