#!/bin/bash

#
# Copyright (c) Dell Inc., or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#

set -ex

checkoutInRepo() {
    pushd $1
    git checkout $2
    popd
}

git clone --no-checkout "$GSTREAMER_REPOSITORY" &
git clone --no-checkout "$LIBNICE_REPOSITORY" &
git clone --no-checkout "$GST_PLUGINS_BASE_REPOSITORY" &
git clone --no-checkout "$GST_PLUGINS_BAD_REPOSITORY" &
git clone --no-checkout "$GST_PLUGINS_GOOD_REPOSITORY" &
git clone --no-checkout "$GST_PLUGINS_UGLY_REPOSITORY" &
git clone --no-checkout "$GST_LIBAV_REPOSITORY" &
git clone --no-checkout "$GST_RTSP_SERVER_REPOSITORY" &

wait

checkoutInRepo gstreamer "$GSTREAMER_CHECKOUT"
checkoutInRepo libnice "$LIBNICE_CHECKOUT"
checkoutInRepo gst-plugins-base "$GST_PLUGINS_BASE_CHECKOUT"
checkoutInRepo gst-plugins-bad "$GST_PLUGINS_BAD_CHECKOUT"
checkoutInRepo gst-plugins-good "$GST_PLUGINS_GOOD_CHECKOUT"
checkoutInRepo gst-plugins-ugly "$GST_PLUGINS_UGLY_CHECKOUT"
checkoutInRepo gst-libav "$GST_LIBAV_CHECKOUT"
checkoutInRepo gst-rtsp-server "$GST_RTSP_SERVER_CHECKOUT"
