#!/bin/bash

#
# Copyright (c) Dell Inc., or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#

set -ex

git clone --no-checkout "$GSTREAMER_REPOSITORY"
pushd gstreamer
git checkout "$GSTREAMER_CHECKOUT"
popd

git clone --no-checkout "$LIBNICE_REPOSITORY"
pushd libnice
git checkout "$LIBNICE_CHECKOUT"
popd

git clone --no-checkout "$GST_PLUGINS_BASE_REPOSITORY"
pushd gst-plugins-base
git checkout "$GST_PLUGINS_BASE_CHECKOUT"
popd

git clone --no-checkout "$GST_PLUGINS_BAD_REPOSITORY"
pushd gst-plugins-bad
git checkout "$GST_PLUGINS_BAD_CHECKOUT"
popd

git clone --no-checkout "$GST_PLUGINS_GOOD_REPOSITORY"
pushd gst-plugins-good
git checkout "$GST_PLUGINS_GOOD_CHECKOUT"
popd

git clone --no-checkout "$GST_PLUGINS_UGLY_REPOSITORY"
pushd gst-plugins-ugly
git checkout "$GST_PLUGINS_UGLY_CHECKOUT"
popd

git clone --no-checkout "$GST_LIBAV_REPOSITORY"
pushd gst-libav
git checkout "$GST_LIBAV_CHECKOUT"
popd

git clone --no-checkout "$GST_RTSP_SERVER_REPOSITORY"
pushd gst-rtsp-server
git checkout "$GST_RTSP_SERVER_CHECKOUT"
popd
