#
# Copyright (c) Dell Inc., or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#

enabled: true
image:
  # Please change the value accordingly before deployment
  #repository: "gstreamer:pravega-dev"
  repository: devops-repo.isus.emc.com:8116/nautilus/deepstream-dev-pod:faheyc
  pullPolicy: "Always"
ssh:
  authorized_keys: ""
