#
# Copyright (c) Dell Inc., or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#

apiVersion: v1
kind: Service
metadata:
  name: "{{ $.Release.Name }}"
  annotations:
    {{- if $.Values.externalDnsHostnameSuffix }}
    external-dns.alpha.kubernetes.io/hostname: {{ $.Release.Name }}.{{ $.Release.Namespace }}{{ $.Values.externalDnsHostnameSuffix }}
    {{- end }}
spec:
  ports:
  - name: ssh
    port: 22
    targetPort: 22
    protocol: TCP
  selector:
    app: "{{ $.Release.Name }}"
  type: LoadBalancer
