#
# Copyright (c) Dell Inc., or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#

enabled: true
image:
  # Please change the value accordingly before deployment
  repository: "pravega/deepstream:latest"
  pullPolicy: "Always"
appParameters:
  ALLOW_CREATE_SCOPE: "false"
  ADD_MESSAGE_WHEN_NO_OBJECTS_FOUND: "true"
  ENTRYPOINT: "/usr/src/gstreamer-pravega/deepstream/python_apps/deepstream-pravega-demos/pravega-to-object-detection-to-pravega.py"
  HEALTH_CHECK_ENABLED: "true"
  HEALTH_CHECK_IDLE_SECONDS: "30"
  GST_DEBUG: "INFO,pravegasrc:LOG,pravegatc:LOG,pravegasink:LOG,fragmp4pay:LOG,qtdemux:LOG,h264parse:LOG,v4l2:LOG"
  LOG_LEVEL: "10"   # 10=DEBUG,20=INFO
  pravega_client_tls_cert_path: "/etc/ssl/certs/ca-certificates.crt"
  PYTHONUNBUFFERED: "1"
  RUST_LOG: "nvds_pravega_proto=trace,warn"
  START_MODE: "latest"
numReadersPerStream: 1
logPersistentVolumeClaimName: data-project
global:
  pravega:
    stream: "camera1"
    numStreams: 1
